name: pictaker
description: Playing around with camera and file_picker plugins

publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.9.4+19
  file_picker: ^4.5.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: launcher_icon
  ios: false
  image_path: assets/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
